### ISSUE TITLE
logo design Proposal 

### ISSUE THREAD

**Issue by Pelikens** [matt-way/dmmm#1]
Hello! I want to contribute on your project with making free logo design. What do you think about it?

Best Regards,
Ksenia
Graphics Designer

**Comment by matt-way** [comment]
This app was built for a friend, who made the logo that they wanted. Did you try the app out?

**Comment by Pelikens** [comment]
Great! I haven't tried the app but wish you good luck. also ready for collaboration related to graphic design.
